# application: jsonpdataproxy-hrd
# version: 4
runtime: python27
api_version: 1
# we are using CGI atm so can only have threadsafe=false
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: dataproxy.py

